### ISSUE TITLE
Update README with test env setup instructions

### ISSUE THREAD

**Issue by januszm** [rgeo/activerecord-mysql2spatial-adapter#21]
`test/database.yml` 

```yaml
adapter: mysql2spatial
encoding: utf8
reconnect: true
host:     localhost
database: YOUR_DATABASE_NAME
username: YOUR_USER_NAME
password: PASSWORD_OR_NOTHING
```

Works with Ruby versions till 2.3.x (didn't test 2.4)

Requires `mysql2` gem version `0.3.x` because of ActiveRecord 4.1 requirements
